# Generated by Django 5.1.1 on 2025-03-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_rename_logentry_logsheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_cycle_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
