# Generated by Django 5.1.1 on 2025-03-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_logsheet_driver_name_trip_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
